export default {
  Shopify: [
    '12amrun',
    // '18montrose',
    'a-ma-maniere',
    'above the clouds',
    'addictmiami',
    'a life new york',
    'amigo skate shop',
    'amongst few',
    'apbstore',
    'antisocialsocialclub',
    'atmosny',
    'bape-us',
    'bbbranded',
    'bbcicecream-us',
    'bbcicecream-eu',
    'blacksheepskateshop',
    'blkmkt',
    'blendsus',
    'bdgastore',
    'bowsandarrowsberkeley',
    'beatniconline',
    'the canteen',
    'capsuletoronto',
    'centre214',
    'cityblueshop',
    'commonwealth',
    'cncpts',
    'concrete',
    'thedarksideinitiative',
    'deadstock',
    'defcongroup',
    'diamondsupplyco',
    'doomsday',
    'dope-factory',
    'dsm-eu',
    'dsm-us',
    'exclucitylife',
    'extrabutterny',
    'fearofgod',
    'featuresneakerboutique',
    'ficegallery',
    'flatspot',
    'freshragsfl',
    'funkoshop',
    'ghostlifestyle',
    'hanon',
    'havenshop',
    'highsandlows',
    'justdon',
    'kith',
    'kongonline',
    'kyliecosmetics',
    'laceupnyc',
    'lapstoneandhammer',
    'toytokyo',
    'leaders1354',
    'machusonline',
    'manorphx',
    'menuskateshop',
    'minishopmadrid',
    'mondotees',
    'nocturnalskateshop',
    'noirfonce',
    'notre',
    'nrml',
    'octobersveryown-us',
    'octobersveryown-ca',
    'octobersveryown-uk',
    'offthehook',
    'oipolloi',
    'oneness287',
    'over9000',
    'oqium',
    'packershoes',
    'palace-uk',
    'palace-us',
    'pampamlondon',
    'par5 milano',
    'philipbrownemenswear',
    'properlbc',
    'publicschoolnyc',
    'reigningchamp',
    'renarts',
    'rimenyc',
    'rise45',
    'rockcitykicks',
    'rooneyshop',
    'rooted',
    'rsvpgallery',
    'saintalfred',
    'shoegallerymiami',
    'unionjordan',
    'shopnicekicks',
    'sneakerpolitics',
    'sneakerworldshop',
    'socialstatuspgh',
    'soleclassics',
    'solefly',
    'solestop',
    'suede-store',
    'super7',
    'sukamii',
    'swanstreet',
    'thepremierstore',
    'trophyroomstore',
    'undefeated',
    'unknwn',
    'urbanindustry',
    'westnyc',
    'wishatl',
    'worldofhombre',
    'xhibition'
  ],
  Supreme: ['supreme-eu', 'supreme-us', 'supreme-autofill'],
  Other: [
    'asphaltgold',
    'overkill'
    // 'ssense'
    // 'sotostore'
  ]
};
